# Generated by Django 5.2 on 2025-04-26 04:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('company_name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('salary_range', models.CharField(blank=True, max_length=100, null=True)),
                ('job_url', models.URLField(max_length=500, unique=True)),
                ('source', models.CharField(help_text='e.g., LinkedIn, Indeed, Company Website', max_length=100)),
                ('date_posted_source', models.DateTimeField(blank=True, help_text='Original posting date if available', null=True)),
                ('date_added_db', models.DateTimeField(default=django.utils.timezone.now, help_text='Date added to our database')),
            ],
            options={
                'ordering': ['-date_added_db'],
            },
        ),
    ]
